-- =====================================================================
--  HỆ THỐNG TƯỚI CÂY THÔNG MINH IoT — SCHEMA DATABASE (Supabase / PostgreSQL)
--  Chạy toàn bộ file này 1 lần trong Supabase → SQL Editor → Run.
--  Chạy lại nhiều lần cũng an toàn (dùng IF NOT EXISTS / OR REPLACE).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. NGƯỜI DÙNG (quản lý người dùng)
--    Đặt tên app_users để không lẫn với bảng auth.users có sẵn của Supabase.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app_users (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email           TEXT NOT NULL UNIQUE,                 -- luôn lưu chữ thường
    password_hash   TEXT NOT NULL,                        -- bcrypt, không bao giờ lưu mật khẩu gốc
    full_name       TEXT NOT NULL DEFAULT '',
    phone           TEXT,
    role            TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,        -- admin có thể khoá tài khoản
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- 2. THIẾT BỊ (quản lý thiết bị) — mỗi dòng là 1 bộ ESP32
--    Gồm 3 nhóm cột: thông tin, CẤU HÌNH MONG MUỐN (web gửi xuống),
--    và TRẠNG THÁI MỚI NHẤT (ESP32 báo lên).
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devices (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id        UUID REFERENCES app_users(id) ON DELETE SET NULL,
    name            TEXT NOT NULL,
    location        TEXT NOT NULL DEFAULT '',
    api_key_hash    TEXT NOT NULL UNIQUE,                 -- SHA-256 của khoá thiết bị
    api_key_hint    TEXT NOT NULL DEFAULT '',             -- 4 ký tự cuối để nhận diện

    -- Cấu hình điều khiển
    mode            TEXT NOT NULL DEFAULT 'auto' CHECK (mode IN ('auto', 'manual')),
    manual_pump     BOOLEAN NOT NULL DEFAULT FALSE,       -- trạng thái bơm mong muốn ở chế độ MANUAL
    soil_low        INT NOT NULL DEFAULT 35 CHECK (soil_low  BETWEEN 0 AND 100), -- đất < ngưỡng này → BẬT bơm
    soil_high       INT NOT NULL DEFAULT 60 CHECK (soil_high BETWEEN 0 AND 100), -- đất ≥ ngưỡng này → TẮT bơm
    max_pump_sec    INT NOT NULL DEFAULT 60  CHECK (max_pump_sec BETWEEN 5 AND 3600),  -- chạy tối đa mỗi lần
    cooldown_sec    INT NOT NULL DEFAULT 300 CHECK (cooldown_sec BETWEEN 0 AND 86400), -- nghỉ tối thiểu giữa 2 lần tưới AUTO
    config_version  INT NOT NULL DEFAULT 1,               -- tăng mỗi khi web đổi cấu hình
    applied_version INT NOT NULL DEFAULT 0,               -- phiên bản cấu hình ESP32 đang chạy
    CONSTRAINT soil_threshold_order CHECK (soil_low < soil_high),

    -- Trạng thái mới nhất do ESP32 báo lên
    temperature     NUMERIC(5, 2),
    humidity        NUMERIC(5, 2),
    soil_moisture   INT,
    soil_raw        INT,                                  -- giá trị ADC thô, dùng để hiệu chuẩn
    pump_state      BOOLEAN NOT NULL DEFAULT FALSE,
    firmware        TEXT,
    local_ip        TEXT,
    rssi            INT,
    last_seen       TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_devices_owner ON devices (owner_id);

-- ---------------------------------------------------------------------
-- 3. LỊCH SỬ CẢM BIẾN (chuỗi thời gian, mặc định 1 dòng/phút/thiết bị)
--    Lưu thời gian dạng TIMESTAMPTZ chuẩn (UTC); trình duyệt tự đổi sang giờ Việt Nam.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sensor_readings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id       UUID NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    temperature     NUMERIC(5, 2),                        -- NULL nếu DHT11 đọc lỗi
    humidity        NUMERIC(5, 2),
    soil_moisture   INT,
    pump_state      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_readings_device_time ON sensor_readings (device_id, created_at DESC);

-- ---------------------------------------------------------------------
-- 4. NHẬT KÝ BƠM (mỗi lần bơm bật/tắt và lý do)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pump_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id       UUID NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    pump_on         BOOLEAN NOT NULL,
    source          TEXT NOT NULL DEFAULT 'unknown',     -- auto | manual | safety | local | boot
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pump_events_device_time ON pump_events (device_id, created_at DESC);

-- ---------------------------------------------------------------------
-- 5. HÀM GỘP DỮ LIỆU CHO BIỂU ĐỒ
--    Trả về trung bình theo từng "khoảng" (bucket) để biểu đồ 7 ngày
--    không phải tải hàng chục nghìn điểm.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION readings_bucketed(
    p_device     UUID,
    p_from       TIMESTAMPTZ,
    p_to         TIMESTAMPTZ,
    p_bucket_sec INT
)
RETURNS TABLE (
    bucket        TIMESTAMPTZ,
    temperature   NUMERIC,
    humidity      NUMERIC,
    soil_moisture NUMERIC,
    pump_ratio    NUMERIC
)
LANGUAGE sql STABLE
AS $$
    SELECT date_bin(make_interval(secs => GREATEST(p_bucket_sec, 60)), r.created_at,
                    TIMESTAMPTZ '2000-01-01 00:00:00+00')       AS bucket,
           ROUND(AVG(r.temperature), 1)                         AS temperature,
           ROUND(AVG(r.humidity), 1)                            AS humidity,
           ROUND(AVG(r.soil_moisture), 1)                       AS soil_moisture,
           ROUND(AVG(CASE WHEN r.pump_state THEN 1 ELSE 0 END), 2) AS pump_ratio
    FROM sensor_readings r
    WHERE r.device_id = p_device
      AND r.created_at >= p_from
      AND r.created_at <  p_to
    GROUP BY 1
    ORDER BY 1;
$$;

-- ---------------------------------------------------------------------
-- 6. BẢO MẬT
--    Bật RLS và KHÔNG tạo policy nào → khoá "anon/publishable" không đọc
--    được gì. Chỉ backend (dùng khoá service_role / secret) truy cập được.
--    Trình duyệt luôn đi qua backend, không bao giờ gọi thẳng Supabase.
-- ---------------------------------------------------------------------
ALTER TABLE app_users       ENABLE ROW LEVEL SECURITY;
ALTER TABLE devices         ENABLE ROW LEVEL SECURITY;
ALTER TABLE sensor_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE pump_events     ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON app_users, devices, sensor_readings, pump_events FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION readings_bucketed(UUID, TIMESTAMPTZ, TIMESTAMPTZ, INT) FROM PUBLIC, anon, authenticated;

GRANT ALL ON app_users, devices, sensor_readings, pump_events TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
GRANT EXECUTE ON FUNCTION readings_bucketed(UUID, TIMESTAMPTZ, TIMESTAMPTZ, INT) TO service_role;
